(ewadd x (ewadd y z))  (ewadd (ewadd x y) z)
(ewadd x y)  (ewadd y x)
(ewmul x (ewmul y z))  (ewmul (ewmul x y) z)
(ewmul x y)  (ewmul y x)
(ewmul (ewadd x y) z)  (ewadd (ewmul x z) (ewmul y z))
(smul (smul x y) w)  (smul x  (smul y w))
(smul (ewadd x y) w)  (ewadd (smul x w)  (smul y w))
(smul (ewmul x y) w)  (ewmul x  (smul y w))
(transpose (transpose x))  x
(transpose (ewadd x y))  (ewadd (transpose x)  (transpose y))
(transpose (ewmul x y))  (ewmul (transpose x)  (transpose y))
(smul (transpose x) w)  (transpose (smul x w))
(matmul x (matmul y z))  (matmul (matmul x y) z)
(smul (matmul x y) w)  (matmul x  (smul y w))
(matmul x (ewadd y z))  (ewadd (matmul x y) (matmul x z))
(transpose (matmul x y))  (matmul (transpose y)  (transpose x))
(conv2d sx sy p c (smul x w) y)  (conv2d sx sy p c x (smul y w))
(smul (conv2d sx sy p 0 x y) w)  (conv2d sx sy p 0 (smul x w) y)
(conv2d sx sy p 0 x (ewadd y z))  (ewadd (conv2d sx sy p 0 x y) (conv2d sx sy p 0 x z))
(conv2d sx sy p 0 (ewadd x y) z)  (ewadd (conv2d sx sy p 0 x z) (conv2d sx sy p 0 y z))
(conv2d sx sy 0 c x y)  (conv2d sx sy 0 c x (enlarge kx ky y))
(conv2d sx sy p 2 x y)  (relu (conv2d sx sy p 0 x y))
(relu (transpose x))  (transpose (relu x))
(conv2d sx sy p 0 x (Cpool kx ky))  (poolavg kx ky sx sy p x)
(poolavg kx ky 1 1 0 (Iconv kx ky))  (Cpool kx ky)
(conv2d 1 1 0 0 x (Iconv kx ky))  x
(matmul x   Imatmul )  x
(ewmul x Iewmul)  x
(split_0 a (concat a x y))  x
(split_1 a (concat a x y))  y
(concat 0 (concat 1 x y) (concat 1 z w))  (concat 1 (concat 0 x z) (concat 0 y w))
(concat a (smul x w) (smul y w))  (smul (concat a x y) w)
(concat a (ewadd x y) (ewadd z w))  (ewadd (concat a x z) (concat a y w))
(concat a (ewmul x y) (ewmul z w))  (ewmul (concat a x z) (concat a y w))
(concat a (relu x) (relu y))  (relu (concat a x y))
(concat 1 (transpose x) (transpose y))  (transpose (concat 0 x y))
(concat 1 (matmul x y) (matmul x z))  (matmul x (concat 1 y z))
(matmul (concat 1 x z) (concat 0 y w))  (ewadd (matmul x y) (matmul z w))
(concat 0 (conv2d sx sy p c x z) (conv2d sx sy p c y z))  (conv2d sx sy p c (concat 0 x y) z)
(concat 1 (conv2d sx sy p c x y) (conv2d sx sy p c x z))  (conv2d sx sy p c x (concat 0 y z))
(conv2d sx sy p 0 (concat 1 x z) (concat 1 y w))  (ewadd (conv2d sx sy p 0 x y) (conv2d sx sy p 0 z w))
(concat 1 (poolavg kx ky sx sy p x) (poolavg kx ky sx sy p y))  (poolavg kx ky sx sy p (concat 1 x y))
(concat 0 (poolmax kx ky sx sy p x) (poolmax kx ky sx sy p y))  (poolmax kx ky sx sy p (concat 0 x y))
(concat 1 (poolmax kx ky sx sy p x) (poolmax kx ky sx sy p y))  (poolmax kx ky sx sy p (concat 1 x y))
